<template>
  <div>
    <div
      id="report"
      class="report"
    >
      <div class="flex">
        <div class="flex-1 mr-5">
          <div class="report-block__header">
            <div>
              Address information
            </div>
            <button
              v-if="addressData.inMonitoring"
              v-tooltip="'This wallet address is being monitored, you are able to receive fast and detailed reports as well as alerts in case of new incoming transactions, new counterparties, or AML/CTF risks identified. This report was generated by using the last 1000 incoming transactions of the requested address.'"
              aria-hidden="true"
              :class="['gl-button', 'gl-button--dark', 'gl-search-box__button', 'ml-3']"
              type="button"
            >
              Monitoring
            </button>
            <gl-icon
              v-else
              v-tooltip="'This report was generated by using the last 10 incoming transactions of the requested address. Add the address to the Monitoring to get a report based on the last 1000 incoming transactions'"
              class="ml-2"
              :height="24"
              name="def-report"
              :width="24"
            />
          </div>
          <div
            v-if="!hasTxs && !addressDataLoading"
            class="wallet-address-wrap mb-4"
          >
            There are no transactions for this address
          </div>
          <div class="wallet-address-wrap mb-4">
            <InfoBlock
              class="mb-4 mr-3"
              label="Wallet address"
              :loading="addressDataLoading"
              :value="addressData.address"
            />
            <InfoBlock
              class="mb-4"
              label="Owner"
              :loading="addressDataLoading"
              :value="ownerLabelFormatter(addressData)"
            />
          </div>
          <div
            v-if="addressData.assumedMeta && addressData.assumedMeta.length > 0"
            class="mb-4"
          >
            <p class="sidebar__analytics-label">
              Tags
            </p>
            <GlTag
              v-for="(tag, index) in addressData.assumedMeta"
              :key="index"
              class="mr-1 mb-1"
              :score="tag.score"
              :tag="capitalizeFirstLetter(tag.name)"
            />
          </div>
          <div class="wrapper">
            <InfoBlock
              class="mb-4"
              label="balance"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.balance
                && toComaSeparate(String(formatBtcAmount(addressData.balance))) || '0'"
            />
            <InfoBlock
              label="Total sent"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.amountSent
                && toComaSeparate(String(formatBtcAmount(addressData.amountSent, true, 3)))"
            />
            <InfoBlock
              label="Total tx sent"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.txSentCount || '0'"
            />
            <InfoBlock
              label="First seen"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.firstSeen
                && formatDate(addressData.firstSeen * 1000, 'dd.MM.yyyy hh:mm a')"
            />
            <InfoBlock
              class="mb-4"
              label="Number of txs"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.txCount || '0'"
            />
            <InfoBlock
              label="Total received"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.amountReceived
                && toComaSeparate(String(formatBtcAmount(addressData.amountReceived, true, 3))) || '0'"
            />
            <InfoBlock
              label="Total tx received"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.txReceivedCount"
            />
            <InfoBlock
              label="Last seen"
              :loading="addressDataLoading"
              :value="addressData
                && addressData.lastSeen
                && formatDate(addressData.lastSeen * 1000, 'dd.MM.yyyy hh:mm a')"
            />
          </div>
          <!--        <InfoBlock-->
          <!--          class="mb-4"-->
          <!--          label="Description"-->
          <!--          :loading="addressDataLoading"-->
          <!--          :value="addressData-->
          <!--            && addressData.description"-->
          <!--        />-->
        </div>
        <div class="report-risk-score">
          <div class="report-block__header">
            Risk score
          </div>
          <semi-circle-progress
            :percentage="Number(totalFunds.toFixed(0))"
            :stroke-bg-color="hex2rgba(findColorByTypeScore(hasTxs ? totalFunds.toFixed(0) : -1), 0.4)"
            :stroke-color="findColorByTypeScore(hasTxs ? totalFunds.toFixed(0) : -1)"
            stroke-linecap="butt"
            :stroke-width="30"
          >
            <div class="total-funds-report">
              <div
                class="risk-score-value"
                :style="`color: ${findColorByTypeScore(hasTxs ? totalFunds : -1)}`"
              >
                {{ hasTxs ? formatFunds(totalFunds, false) : '-' }}
              </div>
            </div>
          </semi-circle-progress>
          <div
            v-if="addressRiskySources.length > 0"
            class="text-center mt-3"
          >
            <strong>{{ formatShare(percent*100) }}</strong> of funds comes from risky sources
          </div>
          <div
            v-else
            class="text-center mt-3"
          >
            No risky sources were found
          </div>
        </div>
      </div>
      <div
        v-if="!calculationLoading && Object.keys(addressData).length > 0"
        class="mb-5"
      >
        <p
          v-if="addressIsOwnerByHightRisk || hasDirectlyMixing || percent * 100 > 0 || addressAreUnidentified || hasTagMoreRiskPoint"
          class="sidebar__analytics-label"
        >
          AML RISK DETECTED
        </p>
        <StatusBlock
          v-if="addressIsOwnerByHightRisk"
          class="mb-2 info-block__wrap"
          label="Address is owned by a high risk entity"
        />
        <StatusBlock
          v-if="hasDirectlyMixing"
          class="mb-2 info-block__wrap"
          label="Address has directly participated in mixing"
        />
        <StatusBlock
          v-if="percent * 100 > 0"
          class="mb-2 info-block__wrap"
          :label="`Address received ${formatShare(percent * 100)} funds from risky sources`"
        />
        <StatusBlock
          v-if="addressAreUnidentified"
          class="mb-2 info-block__wrap"
          label="More than 75% of sources for the address are unidentified"
        />
        <StatusBlock
          v-if="hasTagMoreRiskPoint"
          class="mb-2 info-block__wrap"
          label="Address has directly participated in high risk activities"
        />
      </div>
      <div
        v-if="allDataSource.length > 0 && allDataSourceByOwner.length > 0"
        class="report-block__header"
      >
        Sources of Funds
      </div>
      <div class="flex mb-4 flex-wrap">
        <div class="flex-1">
          <PieDataList
            :data="allDataSource"
            :loading="calculationLoading"
            title="By Type"
            track-by-label="funds.type"
            track-by-label-support="funds.name"
          />
        </div>
        <div class="flex-1">
          <PieDataList
            :data="allDataSourceByOwner"
            :loading="calculationLoading"
            title="By Owner"
            track-by-label="owner"
          />
        </div>
      </div>
    </div>

    <AddressRiskyTable
      v-if="addressRiskySources.length > 0 && !addressDataLoading"
      class="mb-5"
      :data="addressRiskySources"
      :loading="addressDataLoading"
    />
    <AddressUnknownTable
      v-if="addressUnknownSources.length > 0 && !addressDataLoading"
      class="mb-5"
      :data="addressUnknownSources"
      :loading="addressDataLoading"
    />
    <AddressKnownTable
      v-if="addressKnownSources.length > 0 && !addressDataLoading"
      :data="addressKnownSources"
      :loading="addressDataLoading"
    />
  </div>
</template>

<script>
// Components
import InfoBlock from '../../analytics/analytics-info-blocks/components/info-block'
import StatusBlock from "@/pages/report/components/StatusBlock";
import PieDataList from'../components/PieDataList'
import GlTag from '@/components/gl-tag'
import GlIcon from "@/components/gl-icon"
import AddressRiskyTable from "@/pages/report/components/AddressRiskyTable";
import AddressKnownTable from "@/pages/report/components/AddressKnownTable";
import AddressUnknownTable from "@/pages/report/components/AddressUnknownTable";
import semiCircleProgress from 'vue-pithy-progress/lib/semi-circle-progress.umd.min.js'
import 'vue-pithy-progress/lib/semi-circle-progress.css'
// Utils
import {formatDate} from "@/utils/format-date";
import {toComaSeparate} from "@/utils/formatNumber";
import {formatBtcAmount} from "@/utils/format-btc-amount";
import {capitalizeFirstLetter} from "@/utils/text-formatter";
import {findColorByTypeScore, hex2rgba} from "@/utils/cytoskape-ui-rules";
import { formatFunds, ownerLabelFormatter } from "@/utils/report-data-formatter";

export default {
  components: {
    GlIcon,
    InfoBlock,
    StatusBlock,
    PieDataList,
    AddressRiskyTable,
    AddressUnknownTable,
    AddressKnownTable,
    semiCircleProgress,
    GlTag
  },
  props: {
    addressData: {
      type: Object,
      default: () => ({})
    },
    allDataSource: {
      type: Array,
      default: () => []
    },
    addressRiskySources: {
      type: Array,
      default: () => []
    },
    addressKnownSources: {
      type: Array,
      default: () => []
    },
    addressUnknownSources: {
      type: Array,
      default: () => []
    },
    allDataSourceByOwner: {
      type: Array,
      default: () => []
    },
    addressDataLoading: {
      type: Boolean,
      default: false
    },
    calculationLoading: {
      type: Boolean,
      default: false
    },
    percent: {
      type: [Number, String],
      default: 0
    },
    totalFunds: {
      type: [Number, String],
      default: 0
    },
  },
  data() {
    return {
      RISK_POINT: 55
    }
  },
  computed: {
    addressIsOwnerByHightRisk() {
      return (this.addressData.tags && this.addressData.tags.find(tag => tag.score >= this.RISK_POINT))
        || (this.addressData.clusterData.tags && this.addressData.clusterData.tags.find(tag => tag.score >= this.RISK_POINT))
        || this.addressData.type && this.addressData.type.score >= this.RISK_POINT
        || (this.addressData.clusterData.type && this.addressData.clusterData.type.score >= this.RISK_POINT)
    },
    hasDirectlyMixing() {
      return (this.addressData.type && this.addressData.type.name === 'mixing')
          || (this.addressData.clusterData.type && this.addressData.clusterData.type.name === 'mixing')
          || (this.addressData.tags && this.addressData.tags.find(tag => tag.name === 'coin join participant'))
          || (this.addressData.clusterData.tags && this.addressData.clusterData.tags.find(tag => tag.name === 'coin join participant'))
    },
    hasTagMoreRiskPoint() {
      return (this.addressData.tags && this.addressData.tags.find(tag => tag.score >= this.RISK_POINT))
          || (this.addressData.clusterData.tags && this.addressData.clusterData.tags.find(tag => tag.score >= this.RISK_POINT))
    },
    addressAreUnidentified() {
      const sum = this.addressUnknownSources.reduce((acc, { share }) => acc + share, 0)

      return sum * 100 >= 75
    },
    hasTxs() {
      return Boolean(this.addressData.txCount)
    },
  },
  methods: {
    formatDate,
    toComaSeparate,
    capitalizeFirstLetter,
    formatFunds,
    findColorByTypeScore,
    hex2rgba,
    formatBtcAmount,
    ownerLabelFormatter,
    explore(address) {
      const { href } = this.$router.resolve({ name: 'analytics', query: { address } })
      window.open(href, '_blank')
    },
    formatShare(share) {
      const formatted = (share).toFixed(2)
      return formatted === '0.00' ? '< 0.01%' : formatted + '%'
    },
  },
}
</script>

<style>
.wallet-address-wrap {
  display: grid;
  grid-template-columns: 2fr 2fr;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
}
@media screen and (min-width: 1450px) {
  .wrapper {
    grid-template-columns: repeat(4, 2fr);
  }
}

.report-risk-score {
  width: 280px;
}

.total-funds-report {
  position: absolute;
  bottom: 14px;
  left: 50%;
  transform: translate(-50%);
}

.risk-score-value {
  text-align: center;
  font-size: 40px;
  font-weight: bold;
}

.info-block {
  background: #cbe7ff;
  border-radius: 5px;
  padding: 10px 5px;
}

.info-block__wrap {
  padding: 0 5px;
}
</style>
